language: swift
os: osx
osx_image: xcode10.2
sudo: true

matrix:
  include:
  - env: DESTINATION=iphoneos

  - env: DESTINATION=iphonesimulator

install:
  - sudo gem update --system
  - sudo gem install  -n /usr/local/bin cocoapods
  - pod repo update
  - pod install

script:
  - xcodebuild -showsdks
  - if [ $DESTINATION == "iphoneos" ]; then
      xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK -configuration Release build;
    else
      xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK -configuration Release -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.2' build;
    fi
  #- ./docs.sh
