language: swift
os: osx
osx_image: xcode12.1
sudo: true

matrix:
  include:
  - env: TARGET=iOS DESTINATION=iphoneos SWIFT_VERSION=4.2

  - env: TARGET=iOS DESTINATION=iphonesimulator SWIFT_VERSION=4.2

install:
  - sudo gem update --system
  - sudo gem install -n /usr/local/bin cocoapods
  - travis_retry pod repo update --verbose
  - pod install
  - brew install wget
  - sh test.sh

script:
  - xcodebuild -showsdks
  - if [ $DESTINATION == "iphoneos" ]; then
        xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK OTHER_CFLAGS="-fembed-bitcode" -configuration "Release" -sdk iphoneos -arch arm64 clean build;
      else
        xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK -configuration Release -destination 'platform=iOS Simulator,name=iPhone Xs,OS=12.2' build;
      fi
  #- ./docs.sh
