language: swift
osx_image: xcode10.2
sudo: true

matrix:
  include:
  - os: ios
    env: SDK=iphoneos12.2

  - os: ios
    env: SDK=iphonesimulator12.2

install:
  - sudo gem update --system
  - sudo gem install  -n /usr/local/bin cocoapods
  - pod install

script:
  # - xcodebuild -showsdks
  # default build release
  - xcodebuild -workspace ElastosHiveSDK.xcworkspace -scheme ElastosHiveSDK build -sdk ${SDK}
  #- ./docs.sh
