# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HiveExamples' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ElastosHiveSDK', :path => '../../ElastosHiveSDK.podspec'
  pod 'CYLTabBarController'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SVProgressHUD'
  
end
